### ISSUE TITLE
PML Convert 1.4.0: Broken Link

### ISSUE THREAD

**Issue by tajmone** [pml-lang/converter#18]
The download link in the [download page for Windows] is broken:

https://www.pml-lang.dev/downloads/windows/PML%20to%20HTML%20Converter-1.4.0.exe

any attempts to download the `PML to HTML Converter-1.4.0.exe` file result in a non-existing file error.

Also, it's currently hard to learn which is the latest PML Converter version, since it's no mentioned anywhere in the website, not even in the [downloads] or [install] pages — to learn which is the latest version one has to actually hover on the download button and check the URL in the browser status bar.

It would be better if the website were to display the latest PML converter version in the shared top banner, and mention it explicitly in all the download related pages.

Also, since there's no auto-update feature, it would be nice to have some mechanism to be informed on new binary releases, e.g. an RSS feed to which one could subscribe (so any updates will be notified on email clients, etc.).

[download page for Windows]: https://www.pml-lang.dev/downloads/windows/index.html
[downloads]: https://www.pml-lang.dev/downloads/index.html
[install]: https://www.pml-lang.dev/downloads/install.html

**Comment by pxml-lang** [comment]
> The download link in the download page for Windows is broken

I'm very sorry for that. It's now fixed. Back to version 1.3.0. Version 1.4.0 is not ready yet.

> display the latest PML converter version

Yes, will be done.

> mechanism to be informed on new binary releases

Yes, should be done too.

**Comment by pml-lang** [comment]
> display the latest PML converter version

The latest version is now displayed:
- in file [version.txt](https://github.com/pml-lang/converter/blob/main/version.txt)
- on the download pages for [Linux](https://www.pml-lang.dev/downloads/linux/index.html) and [Windows](https://www.pml-lang.dev/downloads/windows/index.html)

> Version 1.4.0 is not ready yet.

Version 1.4.0 is [ready](https://www.pml-lang.dev/downloads/linux/index.html) since a few days.

Changes are documented in [CHANGELOG.txt](https://github.com/pml-lang/converter/blob/main/CHANGELOG.txt)
